deployment:
  tasks:
    - export DEPLOYPATH=/home/pedrosel/lisodossonhos.com
    - export REPOPATH=/home/pedrosel/repositories/lisodossonhos
    - export NODE_OPTIONS=--max_old_space_size=2048

    - cd $REPOPATH

    - /usr/bin/npm ci || /usr/bin/npm install
    - /usr/bin/npm run build

    - /usr/bin/rsync -av --delete $REPOPATH/dist/ $DEPLOYPATH/

    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;